use anyhow::{anyhow, Result};
use circuit_serialize::deserialize::deserialize_proof_with_config;
use circuits::blake::HashValue;
use circuits_stark_verifier::proof::{ComponentShape, ProofConfig};
use starknet_types_core::felt::Felt;
use stwo::core::fields::m31::M31;
use stwo::core::fields::qm31::QM31;
use tzel_core::F as RawF;

// The OutHash derivation shared with the Groth16 path lives in
// `crate::out_hash` (W5 extraction); the STARK bundle's canonical-meta
// check reuses it for the public-output-hash comparison.
use crate::out_hash::compute_output_hash_values;

#[cfg(test)]
const OUTPUT_HASH_VALUES_LEN: usize = 8;
// Canonical metadata for the recursive verifier circuit generated by the
// supported proving pipeline. Proof bundles may choose their public output
// hash, but they must not choose proof-system or circuit identity parameters.
const CANONICAL_VERIFY_META_HEX: &str = include_str!("canonical_verify_meta.hex");

fn raw_to_felt(raw: &RawF) -> Felt {
    Felt::from_bytes_le(raw)
}

#[derive(Clone, Debug, serde::Serialize, serde::Deserialize)]
pub(crate) struct VerifyMeta {
    pub(crate) n_pow_bits: u32,
    pub(crate) n_preprocessed_columns: usize,
    pub(crate) n_trace_columns: usize,
    pub(crate) n_interaction_columns: usize,
    pub(crate) trace_columns_per_component: Vec<usize>,
    pub(crate) interaction_columns_per_component: Vec<usize>,
    pub(crate) cumulative_sum_columns: Vec<bool>,
    pub(crate) n_components: usize,
    pub(crate) fri_log_trace_size: usize,
    pub(crate) fri_log_blowup: u32,
    pub(crate) fri_log_last_layer: u32,
    pub(crate) fri_n_queries: usize,
    pub(crate) fri_fold_step: u32,
    pub(crate) interaction_pow_bits: u32,
    pub(crate) circuit_pow_bits: u32,
    pub(crate) circuit_fri_log_blowup: u32,
    pub(crate) circuit_fri_log_last_layer: u32,
    pub(crate) circuit_fri_n_queries: usize,
    pub(crate) circuit_fri_fold_step: u32,
    pub(crate) circuit_lifting: Option<u32>,
    pub(crate) output_addresses: Vec<usize>,
    pub(crate) n_blake_gates: usize,
    pub(crate) preprocessed_column_ids: Vec<String>,
    pub(crate) preprocessed_root: Vec<u32>,
    pub(crate) public_output_values: Vec<u32>,
}

pub(crate) fn canonical_verify_meta() -> Result<VerifyMeta> {
    let bytes = hex::decode(CANONICAL_VERIFY_META_HEX.trim())
        .map_err(|e| anyhow!("invalid compiled-in canonical verify_meta hex: {e}"))?;
    crate::verify_meta_codec::decode(&bytes)
        .map_err(|e| anyhow!("invalid compiled-in canonical verify_meta: {e}"))
}

#[cfg(test)]
macro_rules! require_canonical_field {
    ($meta:expr, $canonical:expr, $field:ident) => {
        if $meta.$field != $canonical.$field {
            return Err(anyhow!("non-canonical verify_meta {}", stringify!($field)));
        }
    };
}

#[cfg(test)]
pub(crate) fn validate_canonical_verify_meta(meta: &VerifyMeta) -> Result<()> {
    let canonical = canonical_verify_meta()?;

    require_canonical_field!(meta, canonical, n_pow_bits);
    require_canonical_field!(meta, canonical, n_preprocessed_columns);
    require_canonical_field!(meta, canonical, n_trace_columns);
    require_canonical_field!(meta, canonical, n_interaction_columns);
    require_canonical_field!(meta, canonical, trace_columns_per_component);
    require_canonical_field!(meta, canonical, interaction_columns_per_component);
    require_canonical_field!(meta, canonical, cumulative_sum_columns);
    require_canonical_field!(meta, canonical, n_components);
    require_canonical_field!(meta, canonical, fri_log_trace_size);
    require_canonical_field!(meta, canonical, fri_log_blowup);
    require_canonical_field!(meta, canonical, fri_log_last_layer);
    require_canonical_field!(meta, canonical, fri_n_queries);
    require_canonical_field!(meta, canonical, fri_fold_step);
    require_canonical_field!(meta, canonical, interaction_pow_bits);
    require_canonical_field!(meta, canonical, circuit_pow_bits);
    require_canonical_field!(meta, canonical, circuit_fri_log_blowup);
    require_canonical_field!(meta, canonical, circuit_fri_log_last_layer);
    require_canonical_field!(meta, canonical, circuit_fri_n_queries);
    require_canonical_field!(meta, canonical, circuit_fri_fold_step);
    require_canonical_field!(meta, canonical, circuit_lifting);
    require_canonical_field!(meta, canonical, output_addresses);
    require_canonical_field!(meta, canonical, n_blake_gates);
    require_canonical_field!(meta, canonical, preprocessed_column_ids);
    require_canonical_field!(meta, canonical, preprocessed_root);

    if meta.public_output_values.len() != canonical.public_output_values.len() {
        return Err(anyhow!(
            "non-canonical verify_meta public_output_values length"
        ));
    }
    if meta.public_output_values.len() % 4 != 0 {
        return Err(anyhow!(
            "non-canonical verify_meta public_output_values alignment"
        ));
    }
    if meta.public_output_values.len() < OUTPUT_HASH_VALUES_LEN {
        return Err(anyhow!(
            "non-canonical verify_meta public_output_values length"
        ));
    }
    if meta.public_output_values[OUTPUT_HASH_VALUES_LEN..]
        != canonical.public_output_values[OUTPUT_HASH_VALUES_LEN..]
    {
        return Err(anyhow!(
            "non-canonical verify_meta public_output_values suffix"
        ));
    }

    Ok(())
}

fn canonical_verify_meta_for_output_preimage(output_preimage: &[Felt]) -> Result<VerifyMeta> {
    let mut meta = canonical_verify_meta()?;
    let expected_output_hash_values = compute_output_hash_values(output_preimage);
    if meta.public_output_values.len() < expected_output_hash_values.len() {
        return Err(anyhow!(
            "compiled-in canonical verify_meta public_output_values too short"
        ));
    }
    meta.public_output_values[..expected_output_hash_values.len()]
        .copy_from_slice(&expected_output_hash_values);
    Ok(meta)
}

#[derive(Debug, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields)]
pub struct ProofBundle {
    #[serde(with = "tzel_core::hex_bytes")]
    pub proof_bytes: Vec<u8>,
    #[serde(with = "tzel_core::hex_f_vec")]
    pub output_preimage: Vec<RawF>,
}

impl ProofBundle {
    pub fn from_proof_parts(proof_bytes: Vec<u8>, output_preimage: Vec<RawF>) -> Self {
        Self {
            proof_bytes,
            output_preimage,
        }
    }

    pub fn proof_bytes(&self) -> Vec<u8> {
        self.proof_bytes.clone()
    }

    pub fn output_preimage_felts(&self) -> Vec<Felt> {
        self.output_preimage.iter().map(raw_to_felt).collect()
    }

    pub fn verify(&self) -> Result<()> {
        use circuit_verifier::verify::{verify_circuit, CircuitConfig, CircuitPublicData};

        let preimage_felts = self.output_preimage_felts();
        let meta = canonical_verify_meta_for_output_preimage(&preimage_felts)?;

        // M1.6: ProofConfig API changes (stwo-circuits 2591775 → 2bf051f, Jun 2026):
        //   - n_proof_of_work_bits → n_pow_bits
        //   - interaction_pow_bits → n_interaction_pow_bits
        //   - n_components field → derived from component_shapes.len()
        //   - trace_columns_per_component + interaction_columns_per_component → Vec<ComponentShape>
        //   - enabled_bits required (new): the circuit verifier always has all components
        //     active in our usage, so vec![true; n_components].
        let component_shapes: Vec<ComponentShape> = meta
            .trace_columns_per_component
            .iter()
            .zip(meta.interaction_columns_per_component.iter())
            .map(|(&trace_columns, &interaction_columns)| ComponentShape {
                trace_columns,
                interaction_columns,
            })
            .collect();
        let enabled_bits = vec![true; meta.n_components];
        let proof_config = ProofConfig {
            n_pow_bits: meta.n_pow_bits,
            n_preprocessed_columns: meta.n_preprocessed_columns,
            n_trace_columns: meta.n_trace_columns,
            n_interaction_columns: meta.n_interaction_columns,
            component_shapes,
            cumulative_sum_columns: meta.cumulative_sum_columns.clone(),
            enabled_bits,
            fri: circuits_stark_verifier::fri_proof::FriConfig {
                log_trace_size: meta.fri_log_trace_size,
                log_blowup_factor: meta.fri_log_blowup as usize,
                n_queries: meta.fri_n_queries,
                log_n_last_layer_coefs: meta.fri_log_last_layer as usize,
                fold_step: meta.fri_fold_step as usize,
            },
            n_interaction_pow_bits: meta.interaction_pow_bits,
        };

        let qm31_from = |vals: &[u32]| -> QM31 {
            QM31::from_m31(
                M31::from(vals[0]),
                M31::from(vals[1]),
                M31::from(vals[2]),
                M31::from(vals[3]),
            )
        };

        let pr = &meta.preprocessed_root;
        // M1.6: CircuitConfig API changes (stwo-circuits 2591775 → 2bf051f, Jun 2026):
        //   - output_addresses, n_blake_gates fields REMOVED (now derived internally)
        //   - preprocessed_column_ids: Vec<PreProcessedColumnId>
        //       → preprocessed_column_log_sizes: OrderedHashMap<PreProcessedColumnId, u32>
        //   - NEW field n_outputs: derived from output_addresses.len() in old code
        //
        // The compiled-in canonical_verify_meta.hex predates these changes and does not
        // carry per-column log_sizes. For compilation only, we map each column ID to
        // log_trace_size as a placeholder; runtime validation cannot pass against the
        // current canonical blob — a fresh canonical blob must be regenerated separately.
        let circuit_log_trace_size = (meta
            .circuit_lifting
            .unwrap_or(meta.fri_log_trace_size as u32 + meta.fri_log_blowup))
            .saturating_sub(meta.circuit_fri_log_blowup);
        let preprocessed_column_log_sizes: circuits_stark_verifier::order_hash_map::OrderedHashMap<
            stwo_constraint_framework::preprocessed_columns::PreProcessedColumnId,
            u32,
        > = meta
            .preprocessed_column_ids
            .iter()
            .map(|s| {
                (
                    stwo_constraint_framework::preprocessed_columns::PreProcessedColumnId {
                        id: s.clone().into(),
                    },
                    circuit_log_trace_size,
                )
            })
            .collect();
        let circuit_config = CircuitConfig {
            config: stwo::core::pcs::PcsConfig {
                pow_bits: meta.circuit_pow_bits,
                fri_config: stwo::core::fri::FriConfig {
                    log_blowup_factor: meta.circuit_fri_log_blowup,
                    log_last_layer_degree_bound: meta.circuit_fri_log_last_layer,
                    n_queries: meta.circuit_fri_n_queries,
                    fold_step: meta.circuit_fri_fold_step,
                },
                lifting_log_size: meta.circuit_lifting,
            },
            n_outputs: meta.output_addresses.len(),
            preprocessed_column_log_sizes,
            preprocessed_root: HashValue(qm31_from(&pr[0..4]), qm31_from(&pr[4..8])),
        };

        let public_data = CircuitPublicData {
            output_values: meta.public_output_values.chunks(4).map(qm31_from).collect(),
        };

        let compressed = self.proof_bytes();
        let proof_bytes =
            zstd::decode_all(&compressed[..]).map_err(|e| anyhow!("zstd decompress: {e}"))?;
        let mut data = proof_bytes.as_slice();
        let proof = deserialize_proof_with_config(&mut data, &proof_config)
            .map_err(|e| anyhow!("deserialize proof: {e}"))?;

        verify_circuit(circuit_config, proof, public_data)
            .map_err(|e| anyhow!("circuit verification FAILED: {e}"))?;

        Ok(())
    }
}
