//! E2E test for the TZEL aggregation harness.
//!
//! Generates N=4 leaf proofs from a TZEL fixture and reduces them through
//! the binary-tree multiverifier (`tzel_reprover::aggregate`). Asserts the
//! root proof's circuit constraints are satisfied — i.e. all 4 leaf proofs
//! verify recursively inside one STARK.
//!
//! Heavy: each leaf proof takes ~30–60s; the full tree is ~3–6 minutes.
//! Marked `#[ignore]` so it doesn't fire on normal `cargo test`. Run with:
//!
//! ```bash
//! cd services/reprover
//! cargo test --release --test aggregation_e2e -- --ignored --nocapture
//! ```
//!
//! Current status (G3 — partial). The pipeline gets through:
//!   - 4 leaf proofs produced ✓
//!   - AggregationContext built ✓
//!   - First multiverifier circuit constructed ✓ (`is_circuit_valid` passes)
//!   - First multiverifier `prove_circuit_assignment` → PANIC at
//!     `circuit_prover::witness::components::verify_bitwise_xor_8::add_input`
//!     (`input_to_row.get(input).unwrap()` returns `None`).
//!
//! The same harness setup (`build_multiverifier_circuit::<NoValue>` →
//! `PreprocessedCircuit::preprocess_circuit`) works for stwo-circuits'
//! own `test_multiverifier_tree_depth_2` (privacy fixture). It fails for
//! TZEL leaves. Suspected cause: `add_zk_blinding` (applied in
//! `custom_circuit::run_leaf_pipeline_internal`) introduces extra
//! `qm31_ops`/`eq` components that change the inner verifier topology in
//! a way the multiverifier's preprocessed trace doesn't anticipate.
//!
//! To unblock: either drop ZK blinding for aggregation-input leaves and
//! re-add it at the multiverifier root only, or build the multiverifier's
//! preprocessed from a `<NoValue>` topology that explicitly exercises the
//! ZK-blinded shape.

use std::path::PathBuf;

use tzel_reprover::aggregate::{AggregationContext, AggregationNode, AggregationShape, aggregate_tree};
use tzel_reprover::custom_circuit::{LeafArtifacts, produce_leaf_artifacts};
use tzel_reprover::run_privacy_bootloader;

/// Path to the TZEL "shield" Cairo executable fixture (smallest of the
/// three: ~55 KB compiled).
fn shield_fixture() -> PathBuf {
    let workspace_root = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("services/")
        .parent()
        .expect("tzel/")
        .to_path_buf();
    workspace_root.join("cairo/target/dev/run_shield.executable.json")
}

/// Path to the canonical "shield" bench-witness args (pre-generated by
/// `cargo run -p tzel-services --bin gen_proof_bench_args -- shield`).
fn shield_args_fixture() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/run_shield_args.json")
}

/// Run the leaf pipeline once from the fixture, returning the in-memory
/// artifacts needed for aggregation. Each call generates a fresh proof.
fn one_leaf() -> LeafArtifacts {
    let exe = shield_fixture();
    assert!(
        exe.exists(),
        "fixture missing: {} (run `scarb --manifest-path cairo/Scarb.toml build` from tzel root)",
        exe.display()
    );
    let args_path = shield_args_fixture();
    assert!(
        args_path.exists(),
        "args fixture missing: {} (regenerate with `cargo run -p tzel-services --bin gen_proof_bench_args -- shield > tests/fixtures/run_shield_args.json`)",
        args_path.display()
    );
    let (prover_input, output_preimage) =
        run_privacy_bootloader(&exe, None, Some(args_path)).expect("bootloader run failed");
    produce_leaf_artifacts(prover_input, output_preimage).expect("leaf proof generation failed")
}

#[test]
#[ignore]
fn aggregate_four_leaves_to_root() {
    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .try_init();

    // ── Level 0: 4 leaf proofs ───────────────────────────────────────
    eprintln!("[G3] === level 0: generating 4 leaf proofs ===");
    let t0 = std::time::Instant::now();
    let leaves: Vec<LeafArtifacts> = (0..4).map(|i| {
        let t = std::time::Instant::now();
        let leaf = one_leaf();
        eprintln!(
            "[G3]   leaf {} produced in {:?} (cairo {}ms, circuit {}ms)",
            i,
            t.elapsed(),
            leaf.cairo_prove_ms,
            leaf.circuit_prove_ms,
        );
        leaf
    }).collect();
    eprintln!("[G3] 4 leaves produced in {:?}", t0.elapsed());

    // ── Build the aggregation context (per-shape SharedConfig + preprocessed). ─
    let leaf_preprocessed = leaves[0].preprocessed_circuit.clone();
    let leaf_pcs_config = leaves[0].circuit_pcs_config;
    let ctx = AggregationContext::new(leaf_preprocessed, leaf_pcs_config)
        .expect("AggregationContext::new failed");
    eprintln!("[G3] AggregationContext ready");

    // ── Wrap leaves as AggregationNodes. ──────────────────────────────
    let nodes: Vec<AggregationNode> = leaves
        .into_iter()
        .map(|l| AggregationNode {
            proof: l.circuit_proof,
            shape: AggregationShape::Leaf,
        })
        .collect();

    // ── Reduce. ───────────────────────────────────────────────────────
    eprintln!("[G3] === aggregating 4 → 1 ===");
    let t_agg = std::time::Instant::now();
    let root = aggregate_tree(&ctx, nodes).expect("aggregate_tree failed");
    eprintln!("[G3] root proof produced in {:?}", t_agg.elapsed());

    // ── Assertions. ───────────────────────────────────────────────────
    assert_eq!(
        root.shape,
        AggregationShape::Internal,
        "root must have multiverifier shape"
    );
    eprintln!("[G3] ✓ aggregation E2E: 4 TZEL leaves → 1 root via multiverifier tree");
}
