[package]
name = "starkprivacy"
version = "0.2.0"
edition = "2025_12"

[[target.executable]]
name = "run_shield"
function = "starkprivacy::run_shield::main"

[[target.executable]]
name = "run_transfer"
function = "starkprivacy::run_transfer::main"

[[target.executable]]
name = "run_unshield"
function = "starkprivacy::run_unshield::main"

[cairo]
enable-gas = false

[features]
depth16 = []
depth32 = []
depth48 = []
default = ["depth48"]

[dependencies]
cairo_execute = "2.16.1"
