(* ocaml/coq_driver/main.ml — driver for the extracted Rocq xmss_chain_step.

   The extracted module Tzel_wots is generated by Rocq from
   coq/Impl/Extraction.v and copied into this directory by
   coq/Extracted/build.sh before `dune build` runs. The realizations
   for [Hash3] and [pack_adrs_chain] in Extraction.v point to
   [Tzel.Hash.hash3] and [Tzel.Wots.pack_adrs] from the OCaml
   protocol port (this dune executable links the [tzel] library).
   So the extracted [xmss_chain_step] runs the same hashing path as
   the OCaml port — and, transitively, matches the Cairo
   [xmss_chain_step] under the existing cross-impl interop check.

   CLI: 5 args — x and pub_seed as 64-char hex (32 bytes each), and
   key_idx, chain_idx, step as decimal ints. Prints the result as
   64-char hex on stdout. *)

let parse_hex_felt s =
  if String.length s <> 64 then begin
    Printf.eprintf "expected 64-char hex felt, got %d chars\n" (String.length s);
    exit 2
  end;
  let bytes = Bytes.create 32 in
  for i = 0 to 31 do
    let nybble c =
      match c with
      | '0'..'9' -> Char.code c - Char.code '0'
      | 'a'..'f' -> Char.code c - Char.code 'a' + 10
      | 'A'..'F' -> Char.code c - Char.code 'A' + 10
      | _ ->
        Printf.eprintf "bad hex char %C\n" c;
        exit 2
    in
    let hi = nybble s.[2 * i] in
    let lo = nybble s.[2 * i + 1] in
    Bytes.set_uint8 bytes i ((hi lsl 4) lor lo)
  done;
  bytes

let print_hex_felt b =
  for i = 0 to 31 do
    Printf.printf "%02x" (Bytes.get_uint8 b i)
  done;
  print_newline ()

let () =
  let argv = Sys.argv in
  if Array.length argv <> 6 then begin
    prerr_endline
      "usage: main <x_hex64> <pub_seed_hex64> <key_idx> <chain_idx> <step>";
    exit 2
  end;
  let x = parse_hex_felt argv.(1) in
  let pub_seed = parse_hex_felt argv.(2) in
  let key_idx = int_of_string argv.(3) in
  let chain_idx = int_of_string argv.(4) in
  let step = int_of_string argv.(5) in
  let result =
    Tzel_wots.xmss_chain_step x pub_seed key_idx chain_idx step
  in
  print_hex_felt result
