//! v18 DAL-free submission **producer** (track W4).
//!
//! `docs/SNARK-SUBMISSION-DESIGN.md` defines the consumer side: the kernel
//! reassembles staged chunks (`StageChunk`), seals them by payload hash,
//! and applies a batch of declared ops bound to one Groth16-wrapped mv-root
//! proof (`SubmitOps`). This module is the inverse — the wallet/operator
//! side that *produces* those messages:
//!
//! 1. [`build_tree_binding`] — given N ops' bootloader `output_preimage`s,
//!    builds the aggregation-tree [`KernelTreeBinding`] (real ops as
//!    `DeclaredOp` slots, padding as `Opaque` slots duplicating op 0's
//!    leaf to fill `2^depth`) and derives the matching wrap public inputs
//!    (`tree_roots`, `out_hash`) via the SAME verifier walk the kernel runs
//!    ([`tzel_verifier::snark::derive_mv_root_publics`]). A batch of size 1
//!    is just `depth = 1` with one declared slot + one opaque duplicate.
//! 2. [`chunk_payload`] — splits an oversized payload into
//!    `MAX_STAGE_CHUNK_BYTES`-bounded [`KernelStageChunk`]s sharing one
//!    `payload_hash = hash(payload)` (the exact value the kernel checks at
//!    seal time).
//! 3. [`build_op_submission`] — assembles, for a batch of [`OpInput`]s, the
//!    full ordered message sequence: one staged-note entry per encrypted
//!    note (`StageChunk`s) followed by the referencing [`KernelSubmitOps`].
//! 4. [`build_staged_config_submission`] — Deliverable B: stages an
//!    oversized signed `ConfigureVerifier`/`ConfigureBridge` envelope across
//!    chunks, then a `SubmitStagedConfig` message referencing the sealed
//!    entry.
//!
//! ## The gnark prover seam
//!
//! [`build_tree_binding`] computes the public inputs the wrap proof MUST
//! attest, but does not produce the proof itself. The 388-byte Groth16 wrap
//! is generated by the gnark prover (`cmd/measure_circuit_verifier` in the
//! sibling `stwo-gnark-tzel` repo, ~6 min on `pk.bin`). Producers obtain it
//! via the [`Groth16WrapProver`] trait: [`build_op_submission`] takes a
//! `&dyn Groth16WrapProver` and calls [`Groth16WrapProver::prove_wrap`] with
//! the derived publics. The trait is the integration seam — production wires
//! a real prover here; tests use [`StubGroth16Prover`] (returns the captured
//! `verifier/testdata/proof.bin` raw gnark bytes, or the kernel skip-verify
//! token). See [`Groth16WrapProver`] for the seam contract.

use tzel_core::kernel_wire::{
    encode_staged_note_payload, KernelInboxMessage, KernelLeafSlot, KernelOpDecl,
    KernelOpDeclBody, KernelStageChunk, KernelStagedConfigRef, KernelStagedNoteRef, KernelSubmitOps,
    KernelTreeBinding, MAX_BATCH_OPS, MAX_GROTH16_PROOF_BYTES, MAX_STAGE_CHUNK_BYTES,
    MAX_TREE_DEPTH,
};
use tzel_core::{hash, EncryptedNote, F};
use tzel_verifier::snark::{
    compute_expected_out_hash_mv, derive_mv_root_publics, leaf_mv_publics_raw,
    pinned_internal_root_lanes, root_lanes_to_bytes, MvLeafSlot, MvNodePublics,
    LEAF_CIRCUIT_ROOT_LANES,
};

/// Raw 32-byte LE felts, as carried on the kernel wire (`Vec<F>`), wrapped
/// into the `Felt` type the verifier derivation expects. The verifier API
/// already accepts `&[RawF]` for declared slots, so the producer can hand
/// it `output_preimage.as_slice()` directly.
type Preimage = Vec<F>;

/// One op the producer is submitting, decomposed into the public fields the
/// `SubmitOps` wire carries (`body`), the op's bootloader output preimage
/// (the leaf↔mv junction input), and its encrypted notes in the canonical
/// per-kind order the kernel re-binds them in (`apply_declared_op`):
///   - shield   `[client_enc, producer_enc]`
///   - transfer `[enc_1, enc_2, enc_3]`
///   - unshield `[enc_change?, enc_fee]` (change present iff `cm_change != 0`).
#[derive(Debug, Clone)]
pub struct OpInput {
    pub body: KernelOpDeclBody,
    pub output_preimage: Preimage,
    pub notes: Vec<EncryptedNote>,
}

impl OpInput {
    /// Expected staged-note count for this op's kind — mirrors the kernel's
    /// `expected_staged_note_count` so the producer fails fast (before any
    /// L1 message is sent) on a malformed op rather than at apply time.
    pub fn expected_note_count(&self) -> usize {
        match &self.body {
            KernelOpDeclBody::Shield { .. } => 2,
            KernelOpDeclBody::Transfer { .. } => 3,
            KernelOpDeclBody::Unshield { cm_change, .. } => {
                if *cm_change == tzel_core::ZERO {
                    1
                } else {
                    2
                }
            }
        }
    }
}

/// The integration seam for the gnark wrap prover.
///
/// `build_tree_binding` derives the public inputs (`tree_roots`,
/// `out_hash`) the wrap circuit must attest; `prove_wrap` turns them into
/// the 388-byte raw gnark proof. THIS is where the real prover plugs in: a
/// production impl shells out to `stwo-gnark-tzel`'s
/// `cmd/measure_circuit_verifier` with `pk.bin` (~6 min) over the aggregated
/// mv-root proof whose publics are exactly `(tree_roots, out_hash)`. The
/// returned bytes are the `groth16_proof` field of `SubmitOps`; the kernel
/// re-frames them into the verifier envelope
/// (`tree_roots ‖ out_hash ‖ raw_gnark`) and runs `verify_snark_tree`.
pub trait Groth16WrapProver {
    /// Produce the raw gnark proof bytes attesting the wrap circuit's
    /// public inputs. `tree_roots[0]` is the mv-root preprocessed root the
    /// binding folds to; `out_hash` is the wrap OutHash over it.
    fn prove_wrap(
        &self,
        tree_roots: &[[u8; 32]; 4],
        out_hash: &[u32; 8],
    ) -> Result<Vec<u8>, String>;
}

/// Test/dev prover that returns pre-baked proof bytes WITHOUT proving.
///
/// Two flavours, matching how the kernel is exercised:
///   - [`StubGroth16Prover::skip_verify`] — the `b"kernel-test-skip-verify"`
///     token the kernel's `verify_submit_ops_proof` short-circuits on under
///     `cfg(test)`/`tzel_insecure_sandbox`. Use for producer round-trip and
///     sandbox smokes that don't run the real Groth16 check.
///   - [`StubGroth16Prover::testdata_proof`] — the captured real 388-byte
///     gnark proof from `verifier/testdata/proof.bin`. Use where a concrete,
///     correctly-shaped proof is required (the binding self-consistency
///     tests). NOTE: this proof was captured over the fixture aggregation
///     tree, so it only *verifies* against that tree's publics — it exists
///     to exercise the wire shape, not to validate an arbitrary binding.
#[derive(Debug, Clone)]
pub struct StubGroth16Prover {
    bytes: Vec<u8>,
}

/// The captured real gnark proof (`verifier/testdata/proof.bin`, 388 bytes).
/// Baked in at compile time so the stub needs no filesystem access.
pub const TESTDATA_PROOF_BIN: &[u8] = include_bytes!("../../../verifier/testdata/proof.bin");

impl StubGroth16Prover {
    /// Returns the kernel skip-verify token (the kernel applies the batch
    /// without running the Groth16 check, under test/sandbox cfg).
    pub fn skip_verify() -> Self {
        Self {
            bytes: b"kernel-test-skip-verify".to_vec(),
        }
    }

    /// Returns the captured real testdata gnark proof bytes.
    pub fn testdata_proof() -> Self {
        Self {
            bytes: TESTDATA_PROOF_BIN.to_vec(),
        }
    }
}

impl Groth16WrapProver for StubGroth16Prover {
    fn prove_wrap(
        &self,
        _tree_roots: &[[u8; 32]; 4],
        _out_hash: &[u32; 8],
    ) -> Result<Vec<u8>, String> {
        Ok(self.bytes.clone())
    }
}

/// The derived aggregation-tree binding plus the wrap public inputs it
/// folds to (the values the gnark prover must attest).
#[derive(Debug, Clone)]
pub struct DerivedBinding {
    pub binding: KernelTreeBinding,
    /// `tree_roots[0]` = the mv-root preprocessed root; entries `1..4` are
    /// left as the root bytes too (the kernel only consults `[0]`, and the
    /// verifier envelope carries all four — the wrap chip's `N_TREES = 4`
    /// public inputs; the real prover fills them, the stub leaves copies).
    pub tree_roots: [[u8; 32]; 4],
    pub out_hash: [u32; 8],
}

/// Choose the minimal tree depth for `n_ops` real ops: the smallest
/// `depth ≥ 1` with `2^depth ≥ n_ops` (depth 1 / 2 slots is the floor, so a
/// single op pads to one declared slot + one opaque duplicate).
fn choose_depth(n_ops: usize) -> Result<u8, String> {
    if n_ops == 0 {
        return Err("cannot build a binding for zero ops".into());
    }
    if n_ops > MAX_BATCH_OPS {
        return Err(format!(
            "too many ops for one batch: {} > {}",
            n_ops, MAX_BATCH_OPS
        ));
    }
    let mut depth: u8 = 1;
    while (1usize << depth) < n_ops {
        depth += 1;
    }
    if depth > MAX_TREE_DEPTH {
        return Err(format!(
            "tree depth {} exceeds MAX_TREE_DEPTH {}",
            depth, MAX_TREE_DEPTH
        ));
    }
    Ok(depth)
}

/// Build the aggregation-tree binding for `op_preimages` (one per declared
/// op, in `ops[]` order) and derive the wrap public inputs.
///
/// Layout: slots `0..n` are `DeclaredOp(i)`; the remaining `2^depth - n`
/// padding slots duplicate op 0's leaf as `Opaque` lanes (the design doc's
/// "duplicate the op's leaf" padding). Every declared op is therefore
/// referenced by at least one slot, satisfying `validate_kernel_submit_ops`.
///
/// `tree_roots` / `out_hash` are derived with the SAME walk the kernel runs
/// ([`derive_mv_root_publics`] + the OutHash equation), so the binding is
/// internally consistent: a wrap proof over these publics will pass
/// `verify_snark_tree`. The proof itself comes from the gnark seam.
pub fn build_tree_binding(op_preimages: &[&[F]]) -> Result<DerivedBinding, String> {
    let n = op_preimages.len();
    let depth = choose_depth(n)?;
    let slot_count = 1usize << depth;

    // Pre-derive op-0's mv publics once: it backs every padding slot.
    let pad_publics: MvNodePublics =
        leaf_mv_publics_raw(LEAF_CIRCUIT_ROOT_LANES, op_preimages[0]);

    let mut leaf_slots: Vec<KernelLeafSlot> = Vec::with_capacity(slot_count);
    let mut walk_slots: Vec<MvLeafSlot<'_>> = Vec::with_capacity(slot_count);
    for slot in 0..slot_count {
        if slot < n {
            leaf_slots.push(KernelLeafSlot::DeclaredOp(slot as u8));
            walk_slots.push(MvLeafSlot::Declared {
                output_preimage: op_preimages[slot],
            });
        } else {
            leaf_slots.push(KernelLeafSlot::Opaque {
                root: pad_publics.preprocessed_root_lanes,
                outputs: pad_publics.output_lanes,
            });
            walk_slots.push(MvLeafSlot::Opaque(pad_publics));
        }
    }

    // Derive the root publics through the kernel-identical walk.
    let internal_roots = pinned_internal_root_lanes(depth)?;
    let root = derive_mv_root_publics(LEAF_CIRCUIT_ROOT_LANES, &internal_roots, &walk_slots)?;
    let root_bytes = root_lanes_to_bytes(&root.preprocessed_root_lanes);
    let out_hash = compute_expected_out_hash_mv(&root_bytes, &root.output_lanes);

    // The kernel only reads tree_roots[0]; the wrap envelope carries 4. Fill
    // all four with the root preprocessed-root bytes (the real prover sets
    // the trailing trees from the proof witness; the stub leaves copies).
    let tree_roots = [root_bytes; 4];

    Ok(DerivedBinding {
        binding: KernelTreeBinding { depth, leaf_slots },
        tree_roots,
        out_hash,
    })
}

/// Split `payload` into `MAX_STAGE_CHUNK_BYTES`-bounded chunks, all sharing
/// `payload_hash = hash(payload)` and the chosen `staging_id`. Chunk indices
/// are `0..count`, left to right; the kernel reassembles in index order and
/// seals once `hash(reassembled) == payload_hash`.
///
/// An empty payload is rejected — the kernel rejects empty chunks (an empty
/// durable value doubles as a delete), and there is nothing to stage.
pub fn chunk_payload(staging_id: u64, payload: &[u8]) -> Result<Vec<KernelStageChunk>, String> {
    if payload.is_empty() {
        return Err("cannot stage an empty payload".into());
    }
    let payload_hash = hash(payload);
    let chunks: Vec<&[u8]> = payload.chunks(MAX_STAGE_CHUNK_BYTES).collect();
    let chunk_count = chunks.len();
    if chunk_count > u16::MAX as usize {
        return Err(format!("payload needs {} chunks, exceeds u16", chunk_count));
    }
    Ok(chunks
        .into_iter()
        .enumerate()
        .map(|(index, bytes)| KernelStageChunk {
            staging_id,
            chunk_index: index as u16,
            chunk_count: chunk_count as u16,
            payload_hash,
            bytes: bytes.to_vec(),
        })
        .collect())
}

/// Allocator for per-sender staging ids. The kernel scopes staging entries
/// by `(sender, staging_id)`, so a producer just needs ids unique among its
/// own live entries; a monotone counter is sufficient and lets the operator
/// reuse ids freed by GC/seal-discard over time.
#[derive(Debug, Default)]
pub struct StagingIdAllocator {
    next: u64,
}

impl StagingIdAllocator {
    pub fn new(start: u64) -> Self {
        Self { next: start }
    }
    pub fn alloc(&mut self) -> u64 {
        let id = self.next;
        self.next = self.next.wrapping_add(1);
        id
    }
}

/// The full ordered message sequence for a v18 op submission: every staged
/// chunk first (so the entries are sealed by the time `SubmitOps` lands),
/// then the single referencing `SubmitOps`. Submit in `messages` order.
#[derive(Debug, Clone)]
pub struct OpSubmission {
    pub messages: Vec<KernelInboxMessage>,
    /// The `SubmitOps` message, also the last entry of `messages` — exposed
    /// separately for callers that want to inspect/validate it directly.
    pub submit_ops: KernelSubmitOps,
}

/// Build the staged-note `StageChunk`s + `SubmitOps` for a batch of ops.
///
/// Each op's notes are staged one-entry-per-note (the kernel resolves one
/// `KernelStagedNoteRef` to exactly one `encode_staged_note_payload` blob).
/// A single ML-KEM768 note is ~3.6 KiB and fits one chunk, but `chunk_payload`
/// splits larger ones transparently. The op decls reference the sealed
/// entries; the binding + wrap proof come from [`build_tree_binding`] + the
/// gnark seam.
pub fn build_op_submission(
    ops: &[OpInput],
    allocator: &mut StagingIdAllocator,
    prover: &dyn Groth16WrapProver,
) -> Result<OpSubmission, String> {
    if ops.is_empty() {
        return Err("submit-ops requires at least one op".into());
    }
    if ops.len() > MAX_BATCH_OPS {
        return Err(format!(
            "too many ops for one batch: {} > {}",
            ops.len(),
            MAX_BATCH_OPS
        ));
    }

    let mut messages: Vec<KernelInboxMessage> = Vec::new();
    let mut op_decls: Vec<KernelOpDecl> = Vec::with_capacity(ops.len());

    for (op_index, op) in ops.iter().enumerate() {
        let expected = op.expected_note_count();
        if op.notes.len() != expected {
            return Err(format!(
                "op {} has {} notes, expected {} for its kind",
                op_index,
                op.notes.len(),
                expected
            ));
        }
        let mut staged_notes: Vec<KernelStagedNoteRef> = Vec::with_capacity(op.notes.len());
        for note in &op.notes {
            let staging_id = allocator.alloc();
            let payload = encode_staged_note_payload(note)?;
            let payload_hash = hash(&payload);
            for chunk in chunk_payload(staging_id, &payload)? {
                messages.push(KernelInboxMessage::StageChunk(chunk));
            }
            staged_notes.push(KernelStagedNoteRef {
                staging_id,
                payload_hash,
            });
        }
        op_decls.push(KernelOpDecl {
            output_preimage: op.output_preimage.clone(),
            staged_notes,
            body: op.body.clone(),
        });
    }

    // Derive the binding from the ops' preimages, then get the wrap proof.
    let preimages: Vec<&[F]> = ops.iter().map(|op| op.output_preimage.as_slice()).collect();
    let derived = build_tree_binding(&preimages)?;
    let groth16_proof = prover.prove_wrap(&derived.tree_roots, &derived.out_hash)?;
    if groth16_proof.is_empty() || groth16_proof.len() > MAX_GROTH16_PROOF_BYTES {
        return Err(format!(
            "gnark prover returned {} proof bytes, must be 1..={}",
            groth16_proof.len(),
            MAX_GROTH16_PROOF_BYTES
        ));
    }

    let submit_ops = KernelSubmitOps {
        ops: op_decls,
        groth16_proof,
        tree_roots: derived.tree_roots,
        out_hash: derived.out_hash,
        binding: derived.binding,
    };
    messages.push(KernelInboxMessage::SubmitOps(submit_ops.clone()));

    Ok(OpSubmission {
        messages,
        submit_ops,
    })
}

/// Build the staged-config message sequence (Deliverable B): chunk the
/// already-encoded signed config envelope (`encode_kernel_inbox_message` of
/// a `ConfigureVerifier`/`ConfigureBridge`), then a `SubmitStagedConfig`
/// referencing the sealed entry. The kernel reassembles the chunks, decodes
/// the inner envelope, and dispatches to the same config-apply code the v17
/// inline arms use.
///
/// `config_envelope` must be the FULL signed-config inbox payload (the bytes
/// the v17 path would have sent inline, had they fit). Returns the chunks
/// followed by the single `SubmitStagedConfig`, in submit order.
pub fn build_staged_config_submission(
    staging_id: u64,
    config_envelope: &[u8],
) -> Result<Vec<KernelInboxMessage>, String> {
    let payload_hash = hash(config_envelope);
    let mut messages: Vec<KernelInboxMessage> = chunk_payload(staging_id, config_envelope)?
        .into_iter()
        .map(KernelInboxMessage::StageChunk)
        .collect();
    messages.push(KernelInboxMessage::SubmitStagedConfig(KernelStagedConfigRef {
        staging_id,
        payload_hash,
    }));
    Ok(messages)
}

#[cfg(test)]
mod tests {
    use super::*;
    use tzel_core::kernel_wire::{
        decode_kernel_inbox_message, encode_kernel_inbox_message, validate_kernel_submit_ops,
    };

    fn sample_note(seed: u8) -> EncryptedNote {
        // A minimally-valid note: the producer only needs encode/decode
        // round-trip, not decryptability. `EncryptedNote::validate` checks
        // field LENGTHS, so we fill each field to its required size.
        use tzel_core::{
            ENCRYPTED_NOTE_BYTES, ML_KEM768_CIPHERTEXT_BYTES, NOTE_AEAD_NONCE_BYTES,
            OUTGOING_RECOVERY_CT_BYTES,
        };
        EncryptedNote {
            ct_d: vec![seed; ML_KEM768_CIPHERTEXT_BYTES],
            tag: 1,
            ct_v: vec![seed.wrapping_add(1); ML_KEM768_CIPHERTEXT_BYTES],
            nonce: vec![seed.wrapping_add(2); NOTE_AEAD_NONCE_BYTES],
            encrypted_data: vec![seed.wrapping_add(3); ENCRYPTED_NOTE_BYTES],
            outgoing_ct: vec![seed.wrapping_add(4); OUTGOING_RECOVERY_CT_BYTES],
        }
    }

    fn felt(n: u8) -> F {
        let mut f = [0u8; 32];
        f[0] = n;
        f
    }

    /// A plausible bootloader preimage — content is irrelevant to the wire
    /// round-trip (the binding derivation hashes whatever is supplied).
    fn sample_preimage(seed: u8) -> Vec<F> {
        (0..6).map(|i| felt(seed.wrapping_add(i))).collect()
    }

    fn shield_op(seed: u8) -> OpInput {
        OpInput {
            body: KernelOpDeclBody::Shield {
                pubkey_hash: felt(seed),
                fee: 100,
                v: 5000,
                producer_fee: 1,
                client_cm: felt(seed.wrapping_add(10)),
                producer_cm: felt(seed.wrapping_add(11)),
            },
            output_preimage: sample_preimage(seed),
            notes: vec![sample_note(seed), sample_note(seed.wrapping_add(1))],
        }
    }

    fn transfer_op(seed: u8) -> OpInput {
        OpInput {
            body: KernelOpDeclBody::Transfer {
                root: felt(seed),
                nullifiers: vec![felt(seed.wrapping_add(20))],
                fee: 100,
                cm_1: felt(seed.wrapping_add(1)),
                cm_2: felt(seed.wrapping_add(2)),
                cm_3: felt(seed.wrapping_add(3)),
            },
            output_preimage: sample_preimage(seed.wrapping_add(40)),
            notes: vec![
                sample_note(seed),
                sample_note(seed.wrapping_add(1)),
                sample_note(seed.wrapping_add(2)),
            ],
        }
    }

    fn unshield_op(seed: u8, with_change: bool) -> OpInput {
        let cm_change = if with_change {
            felt(seed.wrapping_add(5))
        } else {
            tzel_core::ZERO
        };
        let mut notes = Vec::new();
        if with_change {
            notes.push(sample_note(seed.wrapping_add(7)));
        }
        notes.push(sample_note(seed.wrapping_add(8)));
        OpInput {
            body: KernelOpDeclBody::Unshield {
                root: felt(seed),
                nullifiers: vec![felt(seed.wrapping_add(30))],
                v_pub: 1000,
                fee: 100,
                recipient: "tz1burnburnburnburnburnburnburjAYjjX".into(),
                cm_change,
                cm_fee: felt(seed.wrapping_add(6)),
            },
            output_preimage: sample_preimage(seed.wrapping_add(60)),
            notes,
        }
    }

    /// Round-trip every produced message through encode→decode and confirm
    /// the SubmitOps survives `validate_kernel_submit_ops`, then re-derive
    /// the staged-note hashes to confirm they match the ops' refs.
    fn assert_submission_roundtrips(submission: &OpSubmission) {
        for message in &submission.messages {
            let bytes = encode_kernel_inbox_message(message).unwrap();
            let decoded = decode_kernel_inbox_message(&bytes).unwrap();
            // Cheap structural equality via re-encoding (KernelInboxMessage
            // is not PartialEq, but its wire form is canonical).
            assert_eq!(encode_kernel_inbox_message(&decoded).unwrap(), bytes);
        }
        validate_kernel_submit_ops(&submission.submit_ops).unwrap();
    }

    #[test]
    fn single_shield_op_padded_to_depth_1() {
        let mut alloc = StagingIdAllocator::default();
        let prover = StubGroth16Prover::testdata_proof();
        let submission =
            build_op_submission(&[shield_op(0x10)], &mut alloc, &prover).unwrap();

        // One op, 2 notes → 2 StageChunk + 1 SubmitOps = 3 messages.
        assert_eq!(submission.messages.len(), 3);
        let submit = &submission.submit_ops;
        assert_eq!(submit.ops.len(), 1);
        assert_eq!(submit.binding.depth, 1);
        assert_eq!(submit.binding.leaf_slots.len(), 2);
        assert!(matches!(
            submit.binding.leaf_slots[0],
            KernelLeafSlot::DeclaredOp(0)
        ));
        assert!(matches!(
            submit.binding.leaf_slots[1],
            KernelLeafSlot::Opaque { .. }
        ));
        // Shield carries exactly 2 staged-note refs.
        assert_eq!(submit.ops[0].staged_notes.len(), 2);
        // Real testdata proof shape (388 bytes).
        assert_eq!(submit.groth16_proof.len(), 388);
        assert_submission_roundtrips(&submission);
    }

    #[test]
    fn four_op_batch_depth_2_all_referenced() {
        let mut alloc = StagingIdAllocator::default();
        let prover = StubGroth16Prover::testdata_proof();
        let ops = vec![
            shield_op(0x20),
            transfer_op(0x30),
            unshield_op(0x40, true),
            unshield_op(0x50, false),
        ];
        let submission = build_op_submission(&ops, &mut alloc, &prover).unwrap();

        let submit = &submission.submit_ops;
        assert_eq!(submit.ops.len(), 4);
        assert_eq!(submit.binding.depth, 2);
        assert_eq!(submit.binding.leaf_slots.len(), 4);
        // 4 ops fill all 4 slots → every slot is DeclaredOp, no padding.
        for (i, slot) in submit.binding.leaf_slots.iter().enumerate() {
            assert!(matches!(slot, KernelLeafSlot::DeclaredOp(idx) if *idx as usize == i));
        }
        // Per-kind staged-note counts: shield 2, transfer 3, unshield+change 2,
        // unshield no-change 1.
        assert_eq!(submit.ops[0].staged_notes.len(), 2);
        assert_eq!(submit.ops[1].staged_notes.len(), 3);
        assert_eq!(submit.ops[2].staged_notes.len(), 2);
        assert_eq!(submit.ops[3].staged_notes.len(), 1);
        // Total StageChunk messages = 2+3+2+1 = 8, + 1 SubmitOps.
        assert_eq!(submission.messages.len(), 9);
        assert_submission_roundtrips(&submission);
    }

    #[test]
    fn three_op_batch_pads_to_depth_2_with_opaque_slot() {
        let mut alloc = StagingIdAllocator::default();
        let prover = StubGroth16Prover::skip_verify();
        let ops = vec![shield_op(1), transfer_op(2), shield_op(3)];
        let submission = build_op_submission(&ops, &mut alloc, &prover).unwrap();
        let submit = &submission.submit_ops;
        assert_eq!(submit.binding.depth, 2);
        assert_eq!(submit.binding.leaf_slots.len(), 4);
        // Slot 3 is the padding opaque (duplicating op 0).
        assert!(matches!(
            submit.binding.leaf_slots[3],
            KernelLeafSlot::Opaque { .. }
        ));
        assert_submission_roundtrips(&submission);
    }

    #[test]
    fn binding_is_self_consistent_with_verifier_walk() {
        // The producer's derived (tree_roots, out_hash) must equal what the
        // kernel's verify_snark_tree re-derives from the same binding —
        // i.e. the binding's slots fold to tree_roots[0] and the OutHash
        // equation holds. We check the derivation directly here (the full
        // Groth16 check needs a real proof over these publics).
        let ops = vec![shield_op(7), transfer_op(8)];
        let preimages: Vec<&[F]> =
            ops.iter().map(|o| o.output_preimage.as_slice()).collect();
        let derived = build_tree_binding(&preimages).unwrap();

        // Re-run the kernel-side walk over the SAME slots and confirm the
        // root preprocessed-root equals tree_roots[0].
        let walk_slots: Vec<MvLeafSlot<'_>> = derived
            .binding
            .leaf_slots
            .iter()
            .map(|slot| match slot {
                KernelLeafSlot::DeclaredOp(i) => MvLeafSlot::Declared {
                    output_preimage: preimages[*i as usize],
                },
                KernelLeafSlot::Opaque { root, outputs } => MvLeafSlot::Opaque(MvNodePublics {
                    preprocessed_root_lanes: *root,
                    output_lanes: *outputs,
                }),
            })
            .collect();
        let internal = pinned_internal_root_lanes(derived.binding.depth).unwrap();
        let root = derive_mv_root_publics(LEAF_CIRCUIT_ROOT_LANES, &internal, &walk_slots).unwrap();
        assert_eq!(
            root_lanes_to_bytes(&root.preprocessed_root_lanes),
            derived.tree_roots[0]
        );
        let expected_out =
            tzel_verifier::snark::compute_expected_out_hash_mv(&derived.tree_roots[0], &root.output_lanes);
        assert_eq!(expected_out, derived.out_hash);
    }

    #[test]
    fn chunk_payload_splits_and_shares_hash() {
        let payload = vec![0xABu8; MAX_STAGE_CHUNK_BYTES * 2 + 17];
        let chunks = chunk_payload(42, &payload).unwrap();
        assert_eq!(chunks.len(), 3);
        let h = hash(&payload);
        for (i, c) in chunks.iter().enumerate() {
            assert_eq!(c.staging_id, 42);
            assert_eq!(c.chunk_index, i as u16);
            assert_eq!(c.chunk_count, 3);
            assert_eq!(c.payload_hash, h);
            assert!(c.bytes.len() <= MAX_STAGE_CHUNK_BYTES);
        }
        // Reassembly equals the original.
        let mut reassembled = Vec::new();
        for c in &chunks {
            reassembled.extend_from_slice(&c.bytes);
        }
        assert_eq!(reassembled, payload);
    }

    #[test]
    fn empty_payload_is_rejected() {
        assert!(chunk_payload(1, &[]).is_err());
    }

    #[test]
    fn staged_config_submission_chunks_and_references() {
        // A >4KiB opaque config envelope → 2 chunks + 1 SubmitStagedConfig.
        let envelope = vec![0x5Au8; 4500];
        let messages = build_staged_config_submission(99, &envelope).unwrap();
        assert_eq!(messages.len(), 3);
        let h = hash(&envelope);
        match messages.last().unwrap() {
            KernelInboxMessage::SubmitStagedConfig(reff) => {
                assert_eq!(reff.staging_id, 99);
                assert_eq!(reff.payload_hash, h);
            }
            other => panic!("expected SubmitStagedConfig, got {:?}", other),
        }
        // All messages round-trip.
        for m in &messages {
            let b = encode_kernel_inbox_message(m).unwrap();
            let d = decode_kernel_inbox_message(&b).unwrap();
            assert_eq!(encode_kernel_inbox_message(&d).unwrap(), b);
        }
    }
}
