(* Test vector validation: loads JSON vectors generated by either
   implementation and checks that our OCaml outputs match.

   WHAT THIS TESTS vs. WHAT IT CAN'T:

   Deterministic (tested via byte-exact comparison):
   - BLAKE2s with the active protocol personalizations
   - Full key hierarchy from master_sk
   - Per-address: d_j, nk_spend, nk_tag, auth_root/auth_pub_seed (depth-16 XMSS tree), owner_tag
   - ML-KEM 64-byte seed derivation
   - ML-KEM keygen_det: ek and dk bytes from seed (FIPS 203 deterministic)
   - ML-KEM encaps_derand: ss and ct from (ek, coins) (deterministic given coins)
   - ChaCha20-Poly1305 encryption (deterministic given key/nonce/plaintext)
   - Detection tag computation
   - memo_ct_hash (H_memo over encrypted note fields)
   - WOTS+ keygen, sign (from seed, no randomness)
   - Merkle roots from leaves
   - Note commitments, nullifiers
   - Sighash fold
   - Account IDs
   - Canonical wire encoding byte layout
   - Cross-implementation encrypt: full pipeline with derand encaps

   NOT testable via static vectors (malleable/randomized):
   - ML-KEM randomized encaps (different each run by design)
   - STARK proofs (verified via verify_proof, not byte comparison)
   - Any operation that uses /dev/urandom internally

   For the randomized operations, we test the PROPERTY instead:
   - encaps(ek) produces (ss, ct) such that decaps(dk, ct) == ss
   - A proof produced by tzel-prove is accepted by tzel-verify
   These are covered in test_main.ml's unit tests.
*)

let vectors_path =
  let candidates = [
    "../specs/ocaml_vectors/protocol_v1.json";
    "../../specs/ocaml_vectors/protocol_v1.json";
  ] in
  try List.find Sys.file_exists candidates
  with Not_found -> "../specs/ocaml_vectors/protocol_v1.json"

let hex_of_bytes b =
  let buf = Buffer.create (Bytes.length b * 2) in
  Bytes.iter (fun c -> Buffer.add_string buf (Printf.sprintf "%02x" (Char.code c))) b;
  Buffer.contents buf

let bytes_of_hex s = Hex.to_bytes (`Hex s)

let felt_of_hex s =
  let b = bytes_of_hex s in
  assert (Bytes.length b = 32);
  b

let json_string j = match j with `String s -> s | _ -> failwith "expected string"
let json_int j = match j with `Int n -> n | _ -> failwith "expected int"
let json_list j = match j with `List l -> l | _ -> failwith "expected list"
let json_assoc j = match j with `Assoc a -> a | _ -> failwith "expected assoc"
let json_field key j = List.assoc key (json_assoc j)

let check_hex msg expected actual_bytes =
  Alcotest.(check string) msg expected (hex_of_bytes actual_bytes)

(* ── BLAKE2s ── *)

let test_blake2s_vectors json =
  let vectors = json_list (json_field "blake2s" json) in
  List.iteri (fun i v ->
    let input = bytes_of_hex (json_string (json_field "input" v)) in
    let personal = json_string (json_field "personal" v) in
    let expected = json_string (json_field "output" v) in
    let personal_bytes = if personal = "" then Bytes.empty
      else Bytes.of_string personal in
    let actual = Tzel.Blake2s.hash ~personal:personal_bytes input in
    check_hex (Printf.sprintf "blake2s[%d]" i) expected actual
  ) vectors

(* ── Key hierarchy ── *)

let test_key_hierarchy_vectors json =
  let kh = json_field "key_hierarchy" json in
  let master_sk = felt_of_hex (json_string (json_field "master_sk" kh)) in
  let keys = Tzel.Keys.derive master_sk in
  check_hex "nk" (json_string (json_field "nk" kh)) keys.nk;
  check_hex "ask_base" (json_string (json_field "ask_base" kh)) keys.ask_base;
  check_hex "dsk" (json_string (json_field "dsk" kh)) keys.dsk;
  check_hex "incoming_seed" (json_string (json_field "incoming_seed" kh)) keys.incoming_seed;
  check_hex "view_root" (json_string (json_field "view_root" kh)) keys.view_root;
  check_hex "detect_root" (json_string (json_field "detect_root" kh)) keys.detect_root

(* ── Per-address keys ── *)

let test_address_vectors json =
  let kh = json_field "key_hierarchy" json in
  let master_sk = felt_of_hex (json_string (json_field "master_sk" kh)) in
  let keys = Tzel.Keys.derive master_sk in
  let addrs = json_list (json_field "addresses" json) in
  List.iteri (fun i v ->
    let j = json_int (json_field "j" v) in
    let addr = Tzel.Keys.derive_address keys j in
    let prefix = Printf.sprintf "addr[%d]" i in
    check_hex (prefix ^ ".d_j") (json_string (json_field "d_j" v)) addr.d_j;
    check_hex (prefix ^ ".nk_spend") (json_string (json_field "nk_spend" v)) addr.nk_spend;
    check_hex (prefix ^ ".nk_tag") (json_string (json_field "nk_tag" v)) addr.nk_tag;
    check_hex (prefix ^ ".auth_root") (json_string (json_field "auth_root" v)) addr.auth_root;
    check_hex (prefix ^ ".auth_pub_seed") (json_string (json_field "auth_pub_seed" v)) addr.auth_pub_seed;
    let owner_tag = Tzel.Keys.owner_tag addr in
    check_hex (prefix ^ ".owner_tag") (json_string (json_field "owner_tag" v)) owner_tag
  ) addrs

(* ── ML-KEM seed derivation ── *)

let test_mlkem_seed_vectors json =
  let seeds = json_list (json_field "mlkem_seeds" json) in
  List.iteri (fun i v ->
    let kind = json_string (json_field "kind" v) in
    let root = felt_of_hex (json_string (json_field "root" v)) in
    let j = json_int (json_field "j" v) in
    let expected = json_string (json_field "seed" v) in
    let actual = match kind with
      | "view" -> Tzel.Mlkem.derive_view_seed root j
      | "detect" -> Tzel.Mlkem.derive_detect_seed root j
      | _ -> failwith ("unknown mlkem seed kind: " ^ kind) in
    check_hex (Printf.sprintf "mlkem_seed[%d]" i) expected actual
  ) seeds

(* ── ML-KEM deterministic keygen ── *)

let test_mlkem_keygen_vectors json =
  let vectors = json_list (json_field "mlkem_keygen" json) in
  List.iteri (fun i v ->
    let prefix = Printf.sprintf "mlkem_keygen[%d]" i in
    let view_seed = bytes_of_hex (json_string (json_field "view_seed" v)) in
    let (ek_v, _dk_v) = Tzel.Mlkem.keygen_det view_seed in
    check_hex (prefix ^ ".ek_v") (json_string (json_field "ek_v" v)) ek_v;
    let detect_seed = bytes_of_hex (json_string (json_field "detect_seed" v)) in
    let (ek_d, _dk_d) = Tzel.Mlkem.keygen_det detect_seed in
    check_hex (prefix ^ ".ek_d") (json_string (json_field "ek_d" v)) ek_d
  ) vectors

(* ── ML-KEM deterministic encaps ── *)

let test_mlkem_encaps_derand_vectors json =
  let vectors = json_list (json_field "mlkem_encaps_derand" json) in
  List.iteri (fun i v ->
    let prefix = Printf.sprintf "mlkem_encaps[%d]" i in
    let ek = bytes_of_hex (json_string (json_field "ek" v)) in
    let coins = bytes_of_hex (json_string (json_field "coins" v)) in
    let (ss, ct) = Tzel.Mlkem.encaps_derand ek coins in
    check_hex (prefix ^ ".ss") (json_string (json_field "ss" v)) ss;
    check_hex (prefix ^ ".ct") (json_string (json_field "ct" v)) ct
  ) vectors

(* ── ChaCha20-Poly1305 ── *)

let test_chacha20_vectors json =
  let vectors = json_list (json_field "chacha20" json) in
  List.iteri (fun i v ->
    let prefix = Printf.sprintf "chacha20[%d]" i in
    let ss_v = bytes_of_hex (json_string (json_field "ss_v" v)) in
    let value = Int64.of_string (json_string (json_field "v" v)) in
    let rseed = felt_of_hex (json_string (json_field "rseed" v)) in
    let memo = bytes_of_hex (json_string (json_field "memo" v)) in
    let (nonce, encrypted_data) = Tzel.Detection.encrypt_memo ~ss_v ~v:value ~rseed ~memo in
    check_hex (prefix ^ ".nonce") (json_string (json_field "nonce" v)) nonce;
    check_hex (prefix ^ ".encrypted") (json_string (json_field "encrypted_data" v)) encrypted_data
  ) vectors

(* ── Detection tags ── *)

let test_detection_tag_vectors json =
  let vectors = json_list (json_field "detection_tags" json) in
  List.iteri (fun i v ->
    let ss_d = bytes_of_hex (json_string (json_field "ss_d" v)) in
    let expected_tag = json_int (json_field "tag" v) in
    let actual_tag = Tzel.Detection.compute_tag ss_d in
    Alcotest.(check int) (Printf.sprintf "tag[%d]" i) expected_tag actual_tag
  ) vectors

(* ── Memo hash ── *)

let test_memo_ct_hash_vectors json =
  let v = json_field "memo_ct_hash" json in
  let enc : Tzel.Encoding.encrypted_note = {
    ct_d = bytes_of_hex (json_string (json_field "ct_d" v));
    tag = json_int (json_field "tag" v);
    ct_v = bytes_of_hex (json_string (json_field "ct_v" v));
    nonce = bytes_of_hex (json_string (json_field "nonce" v));
    encrypted_data = bytes_of_hex (json_string (json_field "encrypted_data" v));
  } in
  let mch = Tzel.Encoding.compute_memo_ct_hash enc in
  check_hex "memo_ct_hash" (json_string (json_field "memo_ct_hash" v)) mch

(* ── Cross-implementation encrypt ── *)

let test_cross_impl_encrypt_vectors json =
  let v = json_field "cross_impl_encrypt" json in
  (* Reproduce the full pipeline *)
  let ek_v = bytes_of_hex (json_string (json_field "ek_v" v)) in
  let ek_d = bytes_of_hex (json_string (json_field "ek_d" v)) in
  let coins_v = bytes_of_hex (json_string (json_field "coins_v" v)) in
  let coins_d = bytes_of_hex (json_string (json_field "coins_d" v)) in
  let (ss_v, ct_v) = Tzel.Mlkem.encaps_derand ek_v coins_v in
  check_hex "ss_v" (json_string (json_field "ss_v" v)) ss_v;
  check_hex "ct_v" (json_string (json_field "ct_v" v)) ct_v;
  let (ss_d, ct_d) = Tzel.Mlkem.encaps_derand ek_d coins_d in
  check_hex "ss_d" (json_string (json_field "ss_d" v)) ss_d;
  check_hex "ct_d" (json_string (json_field "ct_d" v)) ct_d;
  let value = Int64.of_string (json_string (json_field "v" v)) in
  let rseed = felt_of_hex (json_string (json_field "rseed" v)) in
  let memo = bytes_of_hex (json_string (json_field "memo" v)) in
  let (nonce, encrypted_data) = Tzel.Detection.encrypt_memo ~ss_v ~v:value ~rseed ~memo in
  check_hex "nonce" (json_string (json_field "nonce" v)) nonce;
  check_hex "encrypted_data" (json_string (json_field "encrypted_data" v)) encrypted_data;
  let tag = Tzel.Detection.compute_tag ss_d in
  Alcotest.(check int) "tag" (json_int (json_field "tag" v)) tag;
  let enc : Tzel.Encoding.encrypted_note = { ct_d; tag; ct_v; nonce; encrypted_data } in
  let mch = Tzel.Encoding.compute_memo_ct_hash enc in
  check_hex "memo_ct_hash" (json_string (json_field "memo_ct_hash" v)) mch

(* ── WOTS+ ── *)

let test_wots_vectors json =
  let vectors = json_list (json_field "wots" json) in
  List.iteri (fun i v ->
    let seed = felt_of_hex (json_string (json_field "seed" v)) in
    let pub_seed = felt_of_hex (json_string (json_field "auth_pub_seed" v)) in
    let key_idx = 0 in
    let expected_leaf = json_string (json_field "leaf" v) in
    let pk = Tzel.Wots.keygen ~seed ~pub_seed ~key_idx in
    let leaf = Tzel.Wots.pk_to_leaf ~pub_seed ~key_idx pk in
    let prefix = Printf.sprintf "wots[%d]" i in
    check_hex (prefix ^ ".leaf") expected_leaf leaf;
    (try
       let sighash = felt_of_hex (json_string (json_field "sighash" v)) in
       let expected_sig = json_list (json_field "signature" v) in
       let sig_vals = Tzel.Wots.sign ~seed ~pub_seed ~key_idx sighash in
       List.iteri (fun j expected_chain ->
         check_hex (Printf.sprintf "%s.sig[%d]" prefix j)
           (json_string expected_chain) sig_vals.(j)
       ) expected_sig
     with Not_found -> ())
  ) vectors

(* ── Merkle ── *)

let test_merkle_vectors json =
  let vectors = json_list (json_field "merkle" json) in
  List.iteri (fun i v ->
    let depth = json_int (json_field "depth" v) in
    let leaves = List.map (fun l -> felt_of_hex (json_string l))
      (json_list (json_field "leaves" v)) in
    let expected_root = json_string (json_field "root" v) in
    let root = Tzel.Merkle.root_of_leaves ~depth leaves in
    check_hex (Printf.sprintf "merkle[%d]" i) expected_root root
  ) vectors

(* ── Notes ── *)

let test_note_vectors json =
  let vectors = json_list (json_field "notes" json) in
  List.iteri (fun i v ->
    let d_j = felt_of_hex (json_string (json_field "d_j" v)) in
    let v_val = Int64.of_string (json_string (json_field "v" v)) in
    let rseed = felt_of_hex (json_string (json_field "rseed" v)) in
    let auth_root = felt_of_hex (json_string (json_field "auth_root" v)) in
    let auth_pub_seed = felt_of_hex (json_string (json_field "auth_pub_seed" v)) in
    let nk_tag = felt_of_hex (json_string (json_field "nk_tag" v)) in
    let prefix = Printf.sprintf "note[%d]" i in
    let note = Tzel.Note.create_from_parts ~d_j ~auth_root ~auth_pub_seed ~nk_tag ~v:v_val ~rseed in
    check_hex (prefix ^ ".rcm") (json_string (json_field "rcm" v)) note.rcm;
    check_hex (prefix ^ ".owner_tag") (json_string (json_field "owner_tag" v)) note.owner_tag;
    check_hex (prefix ^ ".cm") (json_string (json_field "cm" v)) note.cm;
    (try
       let nk_spend = felt_of_hex (json_string (json_field "nk_spend" v)) in
       let pos = json_int (json_field "pos" v) in
       let expected_nf = json_string (json_field "nf" v) in
       let nf = Tzel.Note.nullifier nk_spend note.cm pos in
       check_hex (prefix ^ ".nf") expected_nf nf
     with Not_found -> ())
  ) vectors

(* ── Sighash ── *)

let test_sighash_vectors json =
  let vectors = json_list (json_field "sighash" json) in
  List.iteri (fun i v ->
    let items = List.map (fun j -> felt_of_hex (json_string j))
      (json_list (json_field "items" v)) in
    let expected = json_string (json_field "result" v) in
    let result = Tzel.Hash.sighash_fold items in
    check_hex (Printf.sprintf "sighash[%d]" i) expected result
  ) vectors

(* ── Account IDs ── *)

let test_account_id_vectors json =
  let vectors = json_list (json_field "account_ids" json) in
  List.iteri (fun i v ->
    let s = json_string (json_field "string" v) in
    let expected = json_string (json_field "id" v) in
    let id = Tzel.Hash.account_id s in
    check_hex (Printf.sprintf "account_id[%d]" i) expected id
  ) vectors

(* ── Wire encoding ── *)

let test_wire_encoding_vectors json =
  let v = json_field "wire_encoding" json in
  (* We just check the bytes are identical. The Rust side must produce
     the same encode_payment_address, encode_encrypted_note, etc. output
     for the same field values. Since the field values are deterministic
     (derived from master_sk), this is a byte-exact comparison. *)
  let expected_pa = json_string (json_field "payment_address" v) in
  let expected_enc = json_string (json_field "encrypted_note" v) in
  let expected_pn = json_string (json_field "published_note" v) in
  let expected_nm = json_string (json_field "note_memo" v) in
  (* Reconstruct from the same master_sk *)
  let master_sk = Tzel.Felt.of_u64 12345 in
  let keys = Tzel.Keys.derive master_sk in
  let addr = Tzel.Keys.derive_address keys 0 in
  let pa_wire : Tzel.Encoding.payment_address_wire = {
    d_j = addr.d_j; auth_root = addr.auth_root; auth_pub_seed = addr.auth_pub_seed; nk_tag = addr.nk_tag;
    ek_v = addr.ek_v; ek_d = addr.ek_d;
  } in
  check_hex "payment_address" expected_pa (Tzel.Encoding.encode_payment_address pa_wire);
  (* For enc/pn/nm, use the same deterministic pattern *)
  let enc : Tzel.Encoding.encrypted_note = {
    ct_d = Bytes.init 1088 (fun i -> Char.chr (i mod 256));
    tag = 42;
    ct_v = Bytes.init 1088 (fun i -> Char.chr ((i + 50) mod 256));
    nonce = Bytes.make 12 '\xAA';
    encrypted_data = Bytes.init 1080 (fun i -> Char.chr ((i + 100) mod 256));
  } in
  check_hex "encrypted_note" expected_enc (Tzel.Encoding.encode_encrypted_note enc);
  let cm = Tzel.Hash.hash_tag "wire-test-cm" in
  let pn = { Tzel.Encoding.pn_cm = cm; pn_enc = enc } in
  check_hex "published_note" expected_pn (Tzel.Encoding.encode_published_note pn);
  let nm = { Tzel.Encoding.nm_index = 42L; nm_cm = cm; nm_enc = enc } in
  check_hex "note_memo" expected_nm (Tzel.Encoding.encode_note_memo nm)

(* ── Entry point ── *)

let () =
  if not (Sys.file_exists vectors_path) then begin
    Printf.eprintf
       "No test vectors found at %s.\n\
       Generate them from the Rust implementation:\n\
       \n\
       1. From the repo root, run:\n\
          cargo run -p tzel-services --bin gen-test-vectors -- --output specs/ocaml_vectors/protocol_v1.generated.json\n\
       2. Compare or copy that file to %s\n\
       3. Re-run: dune exec test/test_vectors.exe\n\
       \n\
       Or self-check with OCaml-generated vectors:\n\
       \n\
       dune exec test/gen_vectors.exe > ../specs/ocaml_vectors/protocol_v1_ocaml.json\n\
       dune exec test/test_vectors.exe\n"
      vectors_path vectors_path;
    exit 0
  end;
  let json = Yojson.Basic.from_file vectors_path in
  let run name f =
    Alcotest.test_case name `Quick (fun () -> f json) in
  Alcotest.run "tzel-vectors" [
    "blake2s",          [ run "vectors" test_blake2s_vectors ];
    "key_hierarchy",    [ run "vectors" test_key_hierarchy_vectors ];
    "addresses",        [ run "vectors" test_address_vectors ];
    "mlkem_seeds",      [ run "vectors" test_mlkem_seed_vectors ];
    "mlkem_keygen",     [ run "vectors" test_mlkem_keygen_vectors ];
    "mlkem_encaps",     [ run "vectors" test_mlkem_encaps_derand_vectors ];
    "chacha20",         [ run "vectors" test_chacha20_vectors ];
    "detection_tags",   [ run "vectors" test_detection_tag_vectors ];
    "memo_ct_hash",     [ run "vectors" test_memo_ct_hash_vectors ];
    "cross_impl",       [ run "vectors" test_cross_impl_encrypt_vectors ];
    "wots",             [ run "vectors" test_wots_vectors ];
    "merkle",           [ run "vectors" test_merkle_vectors ];
    "notes",            [ run "vectors" test_note_vectors ];
    "sighash",          [ run "vectors" test_sighash_vectors ];
    "account_ids",      [ run "vectors" test_account_id_vectors ];
    "wire_encoding",    [ run "vectors" test_wire_encoding_vectors ];
  ]
