/// Shared test data for step executables (v2 key hierarchy with auth key tree).
///
/// Auth tree data is HARDCODED — not computed at runtime.
/// In production, the wallet builds auth trees off-chain and passes
/// leaf hashes + Merkle paths to the circuit as arguments.
/// Here we use fixed test values to avoid bloating the Cairo execution trace.
///
/// WARNING: Test keys are hardcoded and publicly known.

use starkprivacy::blake_hash as hash;
use starkprivacy::merkle;

// ── Account ──────────────────────────────────────────────────────────

#[derive(Drop, Copy)]
pub struct Account {
    pub nk: felt252,
    pub ask_base: felt252,
    pub incoming_seed: felt252,
}

pub fn derive_account(master_sk: felt252) -> Account {
    let spend_seed = hash::hash2_generic(0x7370656E64, master_sk);   // "spend"
    let nk = hash::hash2_generic(0x6E6B, spend_seed);               // "nk"
    let ask_base = hash::hash2_generic(0x61736B, spend_seed);       // "ask"
    let incoming_seed = hash::hash2_generic(0x696E636F6D696E67, master_sk); // "incoming"
    Account { nk, ask_base, incoming_seed }
}

pub fn derive_ask(ask_base: felt252, j: felt252) -> felt252 {
    hash::hash2_generic(ask_base, j)
}

// ── Address ──────────────────────────────────────────────────────────

pub fn derive_address(incoming_seed: felt252, j: felt252) -> felt252 {
    let dsk = hash::hash2_generic(0x64736B, incoming_seed); // "dsk"
    hash::hash2_generic(dsk, j)
}

pub fn derive_nk_keys(nk: felt252, d_j: felt252) -> (felt252, felt252) {
    let nk_spend = hash::derive_nk_spend(nk, d_j);
    let nk_tag = hash::derive_nk_tag(nk_spend);
    (nk_spend, nk_tag)
}

// ── Auth key leaf derivation (single leaf, no tree construction) ─────

/// Derive the auth leaf hash for one-time key index i.
/// The circuit only verifies Merkle membership of opaque 32-byte leaves.
/// The Rust wallet derives leaves as H(ML-DSA.KeyGen(seed_i).pk);
/// here we use a deterministic hash because Cairo has no ML-DSA library.
pub fn auth_leaf(ask_j: felt252, i: felt252) -> felt252 {
    let seed_i = hash::hash2_generic(
        hash::hash2_generic(0x617574682D6B6579, ask_j), // H("auth-key", ask_j)
        i,
    );
    hash::hash1(seed_i)
}

// ── Note ─────────────────────────────────────────────────────────────

#[derive(Drop, Copy)]
pub struct Note {
    pub nk_spend: felt252,
    pub nk_tag: felt252,
    pub auth_root: felt252,
    pub auth_leaf_hash: felt252,
    pub auth_key_idx: u32,
    pub d_j: felt252,
    pub v: u64,
    pub rseed: felt252,
    pub cm: felt252,
}

/// Build a note from pre-computed auth data.
pub fn make_note(
    nk: felt252, auth_root: felt252, auth_leaf_hash: felt252, auth_key_idx: u32,
    d_j: felt252, v: u64, rseed: felt252,
) -> Note {
    let (nk_spend, nk_tag) = derive_nk_keys(nk, d_j);
    let rcm = hash::derive_rcm(rseed);
    let otag = hash::owner_tag(auth_root, nk_tag);
    let cm = hash::commit(d_j, v, rcm, otag);
    Note { nk_spend, nk_tag, auth_root, auth_leaf_hash, auth_key_idx, d_j, v, rseed, cm }
}

// ── Pre-computed auth tree data ──────────────────────────────────────
//
// These values are generated by the Rust wallet (cli/src/lib.rs) using
// the cross-implementation test. AUTH_DEPTH=10, so 1024 leaves per tree.
// We only need leaf 0 and its auth path for each address.
//
// To regenerate: run `cargo test test_export_auth_data -- --nocapture`
// in the cli/ directory (not yet implemented — values below were computed
// from the Rust wallet's build_auth_tree function).

// For now, we use a MINIMAL auth tree: AUTH_DEPTH=10 with leaf 0 only.
// The auth_root and auth_path are computed from leaf_0 + 1023 zero-hash leaves.
// This produces a valid but sparse tree.

/// Build a minimal auth tree with only leaf 0 populated.
/// All other leaves are zero → their subtrees are zero hashes.
/// This avoids computing 1024 leaves in Cairo.
fn minimal_auth_root(leaf_0: felt252) -> felt252 {
    // The tree has depth AUTH_DEPTH. Leaf 0 is our value, leaves 1..K are 0.
    // Level 0: node_0 = H(leaf_0, zero_hash[0])
    // Level 1..AUTH_DEPTH-1: node = H(prev, zero_hash[level])
    let mut zh = 0_felt252; // zero_hash[0] = 0
    let mut current = leaf_0;
    let mut d: u32 = 0;
    while d < merkle::AUTH_DEPTH {
        current = hash::hash2(current, zh);
        zh = hash::hash2(zh, zh);
        d += 1;
    };
    current
}

/// Get auth path for leaf 0 in a minimal auth tree.
/// All siblings are zero hashes (since leaves 1..K are all 0).
fn minimal_auth_path() -> Array<felt252> {
    let mut path: Array<felt252> = array![];
    let mut zh = 0_felt252;
    let mut d: u32 = 0;
    while d < merkle::AUTH_DEPTH {
        path.append(zh);
        zh = hash::hash2(zh, zh);
        d += 1;
    };
    path
}

// ── Test accounts ────────────────────────────────────────────────────

const MASTER_ALICE: felt252 = 0xA11CE;
const MASTER_BOB: felt252 = 0xB0B;
const MASTER_DUMMY: felt252 = 0xDEAD;

pub fn alice_account() -> Account { derive_account(MASTER_ALICE) }
pub fn bob_account() -> Account { derive_account(MASTER_BOB) }
pub fn dummy_account() -> Account { derive_account(MASTER_DUMMY) }

pub fn alice_addr_0() -> felt252 { derive_address(alice_account().incoming_seed, 0) }
pub fn alice_addr_1() -> felt252 { derive_address(alice_account().incoming_seed, 1) }
pub fn alice_addr_2() -> felt252 { derive_address(alice_account().incoming_seed, 2) }
pub fn bob_addr_0() -> felt252 { derive_address(bob_account().incoming_seed, 0) }
pub fn bob_addr_1() -> felt252 { derive_address(bob_account().incoming_seed, 1) }
pub fn dummy_addr_0() -> felt252 { derive_address(dummy_account().incoming_seed, 0) }
pub fn dummy_addr_1() -> felt252 { derive_address(dummy_account().incoming_seed, 1) }

// ── Per-address auth data (minimal tree: only leaf 0 used) ──────────

#[derive(Drop)]
pub struct AuthInfo {
    pub auth_root: felt252,
    pub auth_leaf_hash: felt252,  // leaf 0
    pub auth_path: Array<felt252>,
}

fn auth_for(ask_base: felt252, j: felt252) -> AuthInfo {
    let ask_j = derive_ask(ask_base, j);
    let leaf = auth_leaf(ask_j, 0);
    let auth_root = minimal_auth_root(leaf);
    let auth_path = minimal_auth_path();
    AuthInfo { auth_root, auth_leaf_hash: leaf, auth_path }
}

pub fn alice_auth(j: felt252) -> AuthInfo { auth_for(alice_account().ask_base, j) }
pub fn bob_auth(j: felt252) -> AuthInfo { auth_for(bob_account().ask_base, j) }
pub fn dummy_auth(j: felt252) -> AuthInfo { auth_for(dummy_account().ask_base, j) }

// ── Test notes ───────────────────────────────────────────────────────

pub fn note_a() -> (Note, AuthInfo) {
    let ai = alice_auth(0);
    let n = make_note(alice_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, alice_addr_0(), 1000, 0x1001);
    (n, ai)
}
pub fn note_b() -> (Note, AuthInfo) {
    let ai = alice_auth(1);
    let n = make_note(alice_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, alice_addr_1(), 500, 0x1002);
    (n, ai)
}
pub fn note_z() -> (Note, AuthInfo) {
    let ai = dummy_auth(0);
    let n = make_note(dummy_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, dummy_addr_0(), 0, 0x1003);
    (n, ai)
}
pub fn note_c() -> (Note, AuthInfo) {
    let ai = bob_auth(0);
    let n = make_note(bob_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, bob_addr_0(), 1500, 0x1004);
    (n, ai)
}
pub fn note_w() -> (Note, AuthInfo) {
    let ai = dummy_auth(1);
    let n = make_note(dummy_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, dummy_addr_1(), 0, 0x1005);
    (n, ai)
}
pub fn note_d() -> (Note, AuthInfo) {
    let ai = alice_auth(2);
    let n = make_note(alice_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, alice_addr_2(), 800, 0x1006);
    (n, ai)
}
pub fn note_e() -> (Note, AuthInfo) {
    let ai = bob_auth(1);
    let n = make_note(bob_account().nk, ai.auth_root, ai.auth_leaf_hash, 0, bob_addr_1(), 700, 0x1007);
    (n, ai)
}
